ccess.cghub:
access.gdc:
access.ega: 
access.icgc: 
access.cghub:
manifest.gdc:
manifest.icgc:
tool.icgc: /icgc/icgc-storage-client/bin/icgc-storage-client
tool.ega: /icgc/ega-download-demo/EgaDemoClient.jar
tool.gdc: /icgc/gdc-data-transfer-tool/gdc-client
tool.cghub: /icgc/genetorrent/bin/gtdownload
download.directory: /icgc/mnt/downloads
udt: true
transport.parallel: 6
transport.memory: 1
logfile: /icgc/mnt/logging/logfile.txt
